### ISSUE TITLE
Change Context

### ISSUE THREAD

**Issue by zawyelwin** [travisghansen/kubernetes-client-php#2]
How Can I change the current context ?

**Comment by travisghansen** [comment]
Thanks for reaching out! It was originally never intended to switch contexts for a client instance so it has been assumed you'd have dedicated files for each context necessary.

Can you describe your scenario to help me understand the use case?

**Comment by zawyelwin** [comment]
I have a config file with multiple clusters and want to loop through the clusters and check some status and grab some contents. Can u give me some suggestions on doing so ? Thanks for the response.

**Comment by travisghansen** [comment]
Ah yeah, that's an interesting use case. Probably best to add a method on the config class that iterates the various contexts. Would this hypothetical code suit your needs (generally speaking)?

```
foreach($config->getContexts() as $context) {
  $client = new Client($context);
  ...
}
```

**Comment by travisghansen** [comment]
@zawyelwin do you intend to run stuff as '1 and done' or are you attempting to build a long-running controller?

**Comment by zawyelwin** [comment]
That will be a long-running controller.

**Comment by travisghansen** [comment]
Ok sounds good. I've got this implemented in `master` FYI. Got a couple more things to consider but likely in the state it will be in for the next release.

**Comment by travisghansen** [comment]
This is done and snapped in version `v0.2.0`.

https://github.com/travisghansen/kubernetes-client-php/blob/master/src/KubernetesClient/Config.php#L231

There are a couple different approaches you can take to the iteration process:

- build a config object and then invoke `getParsedConfigFile()` which is an `array` with a `contexts` key which will have all your contexts including the name
- you can then modify the above object invoking `$config->useContext($contextName)` as appropriate
- you could leave the original config object unaltered but use it for iteration only and create new instances passing in the `contextName` to `public static function BuildConfigFromFile($path = null, $contextName = null)` or just creating it without params and then invoking `useContext($contextName)` on each new object

If you have any questions let me know, I think it will be pretty self-explanatory.
